export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_LOAD_POST: 'SET_LOAD_POST',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_POST_DATA: 'RESET_POST_DATA',
	CREATE_COMMENT: 'CREATE_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
};
